name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *" # update tiap 6 jam
  workflow_dispatch: # bisa dijalankan manual juga

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: akbarjanuar
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push animation to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
